# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/PixelExperience-Devices/kernel_xiaomi_dipper
          kernel-dir: 4.9.186
          kernel-branch: ten
          config: dipper_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 10
          aosp-clang-version: r365631c
          disable-lto: true
          anykernel3: true
